insert into RELIGION(ID,RELIGION_NAME,IS_ACTIVE) value (1,'HINDU',1)
insert into RELIGION(ID,RELIGION_NAME,IS_ACTIVE) value (2,'MUSLIM',1)
insert into RELIGION(ID,RELIGION_NAME,IS_ACTIVE) value (4,'CHRISTIAN',1)
insert into RELIGION(ID,RELIGION_NAME,IS_ACTIVE) value (3,'SIKH',1)
insert into RELIGION(ID,RELIGION_NAME,IS_ACTIVE) value (5,'BUDDH',1)
insert into RELIGION(ID,RELIGION_NAME,IS_ACTIVE) value (6,'JAIN',1)
insert into RELIGION(ID,RELIGION_NAME,IS_ACTIVE) value (7,'ZOROASTRIAN',1)
insert into RELIGION(ID,RELIGION_NAME,IS_ACTIVE) value (8,'OTHER',1)

insert into COUNTRY(ID,NAME,CODE,IS_ACTIVE) value (1,'INDIA','IND',1)

insert into State(ID,NAME,CODE,COUNTRY_ID,IS_ACTIVE) value (1,'UTTAR PRADESH','UP',1,1)

insert into City(ID,NAME,CODE,STATE_ID,IS_ACTIVE) value (1,'SHAHJAHANPUR','SPN',1,1)