package com.brijframework.school.domain;

import java.util.List;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * Role generated by hbm2java
 */
@Entity
@Table(name = "LOGIN_ROLE", uniqueConstraints = @UniqueConstraint(columnNames = "NAME"))
public class LoginRole extends EntityObject<Integer> {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
		
	@Column(name = "NAME", unique = true, nullable = false, length = 50)
	private String name;
	
	@Column(name = "DESCRIPTION", length = 100)
	private String description;

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "loginRole")
	private List<UserRole> userRoles;
	
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public List<UserRole> getUserRoles() {
		return userRoles;
	}

	public void setUserRoles(List<UserRole> userRoles) {
		this.userRoles = userRoles;
	}
	
}
