package com.brijframework.school.domain;

import javax.persistence.Entity;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToOne;
import javax.persistence.Table;

/**
 * UserRole generated by hbm2java
 */
@Entity
@Table(name = "USER_ROLE")
public class UserRole extends EntityObject<Long> {
	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
		@OneToOne
	@JoinColumn(name = "USER_ID")
	private UserLogin userLogin;

	@ManyToOne
	@JoinColumn(name = "ROLE_ID")
	private LoginRole loginRole;

	public UserRole() {
	}
	
}
