package org.brijframework.college.model;

// Generated Sep 18, 2013 11:58:04 PM by Hibernate Tools 4.0.0

import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToOne;
import javax.persistence.Table;

/**
 * UserRole generated by hbm2java
 */
@Entity
@Table(name = "user_role")
public class UserRole extends AbstractPO<UserRoleId> {
	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	@EmbeddedId
	private UserRoleId id;

	@OneToOne
	@JoinColumn(name = "USER_ID", insertable = false,  updatable = false)
	private User user;

	@ManyToOne
	@JoinColumn(name = "ROLE_ID", insertable = false,  updatable = false)
	private LoginRole role;

	public UserRole(int roleId, int userId) {
		this.setId(new UserRoleId(userId, roleId));
	}

	public UserRole() {
	}
	
	public UserRole(UserRoleId id) {
		this.id = id;
	}

	public UserRoleId getId() {
		return this.id;
	}

	public void setId(UserRoleId id) {
		this.id = id;

	}

	public User getUser() {
		return user;
	}

	public void setUser(User user) {
		this.user = user;
	}

	public LoginRole getRole() {
		return role;
	}

	public void setRole(LoginRole role) {
		this.role = role;
	}

}
